
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "comandosleft&|^left+-left*/%rightUMINUSID LITERAL_CURTO LITERAL_FLUTUA TIPO_CURTO TIPO_FLUTUA\n    empty :\n    \n    comandos : comandos comando\n             | empty\n    \n    comando : declaracao_de_variavel ';'\n            | operacao ';'\n    \n    declaracao_de_variavel : TIPO ID '=' operacao\n    \n    operacao : operacao '*' operacao\n             | operacao '/' operacao\n             | operacao '%' operacao\n             | operacao '+' operacao\n             | operacao '-' operacao\n             | operacao '&' operacao\n             | operacao '^' operacao\n             | operacao '|' operacao\n    \n    operacao : '-' operacao %prec UMINUS\n    \n    operacao : LITERAL\n    \n    operacao : ID\n    \n    operacao : '(' operacao ')'\n    \n    TIPO : TIPO_CURTO\n         | TIPO_FLUTUA\n    \n    LITERAL : LITERAL_CURTO\n            | LITERAL_FLUTUA\n    "
    
_lr_action_items = {'-':([0,1,2,3,5,7,8,9,10,13,14,15,16,17,18,19,20,21,22,23,24,26,27,28,29,30,31,32,33,34,35,36,37,38,],[-1,8,-3,-2,21,-17,8,-16,8,-21,-22,-4,-5,8,8,8,8,8,8,8,8,-15,21,-7,-8,-9,-10,-11,21,21,21,8,-18,21,]),'ID':([0,1,2,3,6,8,10,11,12,15,16,17,18,19,20,21,22,23,24,36,],[-1,7,-3,-2,25,7,7,-19,-20,-4,-5,7,7,7,7,7,7,7,7,7,]),'(':([0,1,2,3,8,10,15,16,17,18,19,20,21,22,23,24,36,],[-1,10,-3,-2,10,10,-4,-5,10,10,10,10,10,10,10,10,10,]),'TIPO_CURTO':([0,1,2,3,15,16,],[-1,11,-3,-2,-4,-5,]),'TIPO_FLUTUA':([0,1,2,3,15,16,],[-1,12,-3,-2,-4,-5,]),'LITERAL_CURTO':([0,1,2,3,8,10,15,16,17,18,19,20,21,22,23,24,36,],[-1,13,-3,-2,13,13,-4,-5,13,13,13,13,13,13,13,13,13,]),'LITERAL_FLUTUA':([0,1,2,3,8,10,15,16,17,18,19,20,21,22,23,24,36,],[-1,14,-3,-2,14,14,-4,-5,14,14,14,14,14,14,14,14,14,]),'$end':([0,1,2,3,15,16,],[-1,0,-3,-2,-4,-5,]),';':([4,5,7,9,13,14,26,28,29,30,31,32,33,34,35,37,38,],[15,16,-17,-16,-21,-22,-15,-7,-8,-9,-10,-11,-12,-13,-14,-18,-6,]),'*':([5,7,9,13,14,26,27,28,29,30,31,32,33,34,35,37,38,],[17,-17,-16,-21,-22,-15,17,-7,-8,-9,17,17,17,17,17,-18,17,]),'/':([5,7,9,13,14,26,27,28,29,30,31,32,33,34,35,37,38,],[18,-17,-16,-21,-22,-15,18,-7,-8,-9,18,18,18,18,18,-18,18,]),'%':([5,7,9,13,14,26,27,28,29,30,31,32,33,34,35,37,38,],[19,-17,-16,-21,-22,-15,19,-7,-8,-9,19,19,19,19,19,-18,19,]),'+':([5,7,9,13,14,26,27,28,29,30,31,32,33,34,35,37,38,],[20,-17,-16,-21,-22,-15,20,-7,-8,-9,-10,-11,20,20,20,-18,20,]),'&':([5,7,9,13,14,26,27,28,29,30,31,32,33,34,35,37,38,],[22,-17,-16,-21,-22,-15,22,-7,-8,-9,-10,-11,-12,-13,-14,-18,22,]),'^':([5,7,9,13,14,26,27,28,29,30,31,32,33,34,35,37,38,],[23,-17,-16,-21,-22,-15,23,-7,-8,-9,-10,-11,-12,-13,-14,-18,23,]),'|':([5,7,9,13,14,26,27,28,29,30,31,32,33,34,35,37,38,],[24,-17,-16,-21,-22,-15,24,-7,-8,-9,-10,-11,-12,-13,-14,-18,24,]),')':([7,9,13,14,26,27,28,29,30,31,32,33,34,35,37,],[-17,-16,-21,-22,-15,37,-7,-8,-9,-10,-11,-12,-13,-14,-18,]),'=':([25,],[36,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comandos':([0,],[1,]),'empty':([0,],[2,]),'comando':([1,],[3,]),'declaracao_de_variavel':([1,],[4,]),'operacao':([1,8,10,17,18,19,20,21,22,23,24,36,],[5,26,27,28,29,30,31,32,33,34,35,38,]),'TIPO':([1,],[6,]),'LITERAL':([1,8,10,17,18,19,20,21,22,23,24,36,],[9,9,9,9,9,9,9,9,9,9,9,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comandos","S'",1,None,None,None),
  ('empty -> <empty>','empty',0,'p_empty','grammar.py',21),
  ('comandos -> comandos comando','comandos',2,'p_comandos','grammar.py',26),
  ('comandos -> empty','comandos',1,'p_comandos','grammar.py',27),
  ('comando -> declaracao_de_variavel ;','comando',2,'p_comando','grammar.py',32),
  ('comando -> operacao ;','comando',2,'p_comando','grammar.py',33),
  ('declaracao_de_variavel -> TIPO ID = operacao','declaracao_de_variavel',4,'p_declaracao_de_variavel','grammar.py',39),
  ('operacao -> operacao * operacao','operacao',3,'p_operacao','grammar.py',48),
  ('operacao -> operacao / operacao','operacao',3,'p_operacao','grammar.py',49),
  ('operacao -> operacao % operacao','operacao',3,'p_operacao','grammar.py',50),
  ('operacao -> operacao + operacao','operacao',3,'p_operacao','grammar.py',51),
  ('operacao -> operacao - operacao','operacao',3,'p_operacao','grammar.py',52),
  ('operacao -> operacao & operacao','operacao',3,'p_operacao','grammar.py',53),
  ('operacao -> operacao ^ operacao','operacao',3,'p_operacao','grammar.py',54),
  ('operacao -> operacao | operacao','operacao',3,'p_operacao','grammar.py',55),
  ('operacao -> - operacao','operacao',2,'p_operacao_minus','grammar.py',75),
  ('operacao -> LITERAL','operacao',1,'p_operacao_literal','grammar.py',81),
  ('operacao -> ID','operacao',1,'p_operacao_variavel','grammar.py',87),
  ('operacao -> ( operacao )','operacao',3,'p_operacao_parenteses','grammar.py',95),
  ('TIPO -> TIPO_CURTO','TIPO',1,'p_TIPO','grammar.py',101),
  ('TIPO -> TIPO_FLUTUA','TIPO',1,'p_TIPO','grammar.py',102),
  ('LITERAL -> LITERAL_CURTO','LITERAL',1,'p_LITERAL','grammar.py',108),
  ('LITERAL -> LITERAL_FLUTUA','LITERAL',1,'p_LITERAL','grammar.py',109),
]
